# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ for more details
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build image
          command: |
            docker build . -t thoughtmachine/generic-k8s-webhook:"$CIRCLE_SHA1"

  build_and_release:
    machine: true
    steps:
      - checkout
      - run:
          name: Build image
          command: |
            docker build . -t thoughtmachine/generic-k8s-webhook:"$CIRCLE_SHA1" -t thoughtmachine/generic-k8s-webhook:"$CIRCLE_TAG"
      - run:
          name: Publish image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push thoughtmachine/generic-k8s-webhook:"$CIRCLE_SHA1"
            docker push thoughtmachine/generic-k8s-webhook:"$CIRCLE_TAG"

workflows:
  version: 2
  build-branch:
    jobs:
      - build

  build-on-tag:
    jobs:
      - build_and_release:
          context: conntest-dockerhub-release
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+.*/
            branches:
              ignore: /.*/
