name: Publish Docker 🐳 images 📦 to GitHub Container Registry

on:
  push:
    tags:
      - '**'

jobs:
  build-and-publish-to-ghcr:
    # Explicitly grant the `secrets.GITHUB_TOKEN` permissions.
    permissions:
      # Grant the ability to write to GitHub Packages (push Docker images to
      # GitHub Container Registry).
      packages: write
    name: Build and publish Docker 🐳 images 📦 to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          # This is the user that triggered the Workflow. In this case, it will
          # either be the user whom created the Release or manually triggered
          # the workflow_dispatch.
          username: ${{ github.actor }}
          # `secrets.GITHUB_TOKEN` is a secret that's automatically generated by
          # GitHub Actions at the start of a workflow run to identify the job.
          # This is used to authenticate against GitHub Container Registry.
          # See https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          # for more detailed information.
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true # push the image to ghcr
          tags: |
            ghcr.io/jordipiqueselles/generic-k8s-webhook:${{github.sha}},
            ghcr.io/jordipiqueselles/generic-k8s-webhook:${{github.ref_name}}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
