name: Test PRs
on:
  pull_request:
    types: [labeled] # So that only labelled PRs get run. https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

# Explicitly grant the `secrets.GITHUB_TOKEN` no permissions.
permissions: {}
jobs:
  execute-unittests:
    name: Execute the unittests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Action
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check pyproject.toml
        run: make check-pyproject

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install poetry
        run: python3 -m pip install poetry

      - name: Install Python libraries
        run: poetry install

      - name: Linter
        run: make lint

      - name: Run unittests
        run: make unittests

  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Setup Action
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
